background_blur 1
# CURSOR
cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_shape block
cursor_shape_unfocused hollow


# URL
detect_urls yes
url_style curly


font_family      family="JetBrainsMono Nerd Font Mono"
font_size 11.0
bold_font        auto
italic_font      auto
bold_italic_font auto

tab_bar_style fade
tab_fade 1

include matugen-colors.conf
