# --- Main colors ---
background            #18120c
foreground            #ede0d4

selection_background  #57432b
selection_foreground  #fcdebc
url_color             #bacd9f

color0                #211a13
color1                #ffb4ab
color2                #dec2a2
color3                #bacd9f
color4                #f6bc70
color5                #93000a
color6                #9c8e80
color7                #ede0d4
color8                #3b332b
color9                #ffb4ab
color10               #dec2a2
color11               #bacd9f
color12               #f6bc70
color13               #93000a
color14               #504539
color15               #d3c4b4

# --- UI ---
active_tab_foreground   #462a00
active_tab_background   #f6bc70
inactive_tab_foreground #d3c4b4
inactive_tab_background #211a13

active_border_color     #f6bc70
inactive_border_color   #3b332b
