# --- Main colors ---
background            #131318
foreground            #e5e1e9

selection_background  #474459
selection_foreground  #e4dff9
url_color             #ebb8cf

color0                #1c1b20
color1                #ffb4ab
color2                #c8c3dc
color3                #ebb8cf
color4                #c6c0ff
color5                #93000a
color6                #928f99
color7                #e5e1e9
color8                #35343a
color9                #ffb4ab
color10               #c8c3dc
color11               #ebb8cf
color12               #c6c0ff
color13               #93000a
color14               #47464f
color15               #c8c5d0

# --- UI ---
active_tab_foreground   #2e2960
active_tab_background   #c6c0ff
inactive_tab_foreground #c8c5d0
inactive_tab_background #1c1b20

active_border_color     #c6c0ff
inactive_border_color   #35343a
