# --- Main colors ---
background            #0f1513
foreground            #dee4e0

selection_background  #344c44
selection_foreground  #cde9de
url_color             #a9cbe3

color0                #171d1b
color1                #ffb4ab
color2                #b2ccc2
color3                #a9cbe3
color4                #86d6bf
color5                #93000a
color6                #89938e
color7                #dee4e0
color8                #303634
color9                #ffb4ab
color10               #b2ccc2
color11               #a9cbe3
color12               #86d6bf
color13               #93000a
color14               #3f4945
color15               #bfc9c4

# --- UI ---
active_tab_foreground   #00382d
active_tab_background   #86d6bf
inactive_tab_foreground #bfc9c4
inactive_tab_background #171d1b

active_border_color     #86d6bf
inactive_border_color   #303634
