hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hypridle & hyprsunset")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SSH_AUTH_SOCK")
	hl.exec_cmd("ssh-agent -a $xdg_runtime_dir/ssh-agent.socket")
	hl.exec_cmd("xdg-open 'obsidian://open?vault=Alexandria'")
end)
