#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = awww-daemon
exec-once = hypridle
exec-once = hyprsunset
exec-once = ssh-agent -a $XDG_RUNTIME_DIR/ssh-agent.socket
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SSH_AUTH_SOCK
exec-once = flatpak run md.obsidian.Obsidian
