##############################
### WINDOWS AND WORKSPACES ###
##############################
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}
windowrule {
    name = fix-xwayland-drag
    match:class = ^$
    match:class = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = picture-in-picture
    match:class = ^firefox$
    match:title = ^Picture-in-Picture$

    float = true
    pin = true
    size = 400 225
    move = 100%-420 100%-245
}
